/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

int main(void) {

	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN; // peripheral clock enable register

	//  Output mode, max speed 10 MHz.  MODE13 = 01 ,CNF13 = 00
	GPIOC->CRH &= ~(0xF << 20);
	GPIOC->CRH |= (1 << 20);

	while (1) {

		GPIOC->BSRR = (1 << 29);  // pc13 active low

	}

}
