/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 *Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "i2c.h"
#include "ssd1306.h"
#include <stdint.h>

uint8_t cmd[28] = {0xAE, 0x20, 0x10, 0xB0, 0xC8, 0x00, 0x10, 0x40, 0x81, 0xFF,
                   0xA1, 0xA6, 0xA8, 0x3F, 0xA4, 0xD3, 0x00, 0xD5, 0xF0, 0xD9,
                   0x22, 0xDA, 0x12, 0xDB, 0x20, 0x8D, 0x14, 0xAF};
uint8_t String[] = "HELLO OLED";
int main(void) {
  I2C_Init();

  OLED_SendCommand(cmd, 28);
  //   OLED_WriteChar('C');
  OLED_WriteString(String);

  /* Loop forever */
  for (;;)
    ;
}
