/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "dma.h"
#include "spi.h"
#include "ssd1360.h"
#include "w25q128.h"
#include <stdint.h>

uint8_t buffer[8];
uint8_t src[8] = {0x9F, 0xFF, 0xFF, 0xFF};

int main(void) {

  SPI1_Init();
  dma_init();

  dma_config(src, buffer, 4);
  CS_LOW();
  dma_tranfer();
  while (!(DMA1->ISR & (1 << 5)))
    ; // TCIF2 RX done

  while (SPI1->SR & (1 << 7))
    ; // BSY=0
  CS_HIGH();
  while (1)
    ;
}
