/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "spi.h"
#include "ssd1360.h"
#include "w25q128.h"
#include <stdint.h>

int main(void) {
  uint8_t data[6] = "HELLO";
  uint8_t buffer[6];
  uint16_t len = 6;
  
  SPI1_Init();
  uint32_t id = W25Q128_ReadID();
  // W25Q_EraseSector(0x000000);
  // W25Q_Write(0x000000, data, len);
  // W25Q_Read(0x000000, buffer, len);
  while (1) {
  }
}