/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "spi.h"
#include "ssd1360.h"
#include <stdint.h>
unsigned char arr[18] = "NGUYEN NGOC THANH";
int main(void) {

  SPI1_Init();
  OLED_Init();

  OLED_SendCommand(0xB0);
  OLED_SendCommand(0x00);
  OLED_SendCommand(0x10);

  while (1) {
    OLED_WriteString(arr);
    for (;;)
      ;
  }
}