/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

int main(void) {

	//  peripheral clock enable register
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;

	// PC13 output push-pull 10MHz MODE13 = 01 ,CNF13 = 00
	GPIOC->CRH &= ~(0xF << 20);
	GPIOC->CRH |= (1 << 20);

	// PB12 input pull-up
	GPIOB->CRH &= ~(0xF << 16);
	GPIOB->CRH |= (0x8 << 16); // MODE12 = 00 , CNF12 = 10
	GPIOB->ODR |= (1 << 12); // pull up

	while (1) {

		if (!(GPIOB->IDR & (1 << 12))) {

			GPIOC->ODR ^= (1 << 13);
			for (volatile int i = 0; i < 1000000; i++)
				;

		}
	}

}
